name: Keploy Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  keploy-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Keploy CLI
        run: |
          curl --silent -O -L https://keploy.io/ent/install.sh \
            && source install.sh
      - name: Run Keploy Test Suite
        env:
          KEPLOY_API_KEY: ${{ secrets.KEPLOY_API_KEY }}
        run: |
          export KEPLOY_API_KEY=kep_skxL-1cuY2e3HCGb39WQ-Ch0QZ74quO0nof4k84g_LI && keploy test-suite \
            --app=359356cc-009e-4a27-9963-a7bd3fc114a0 \
            --base-path https://playground.nileslabs.com \
            --cloud \
            --create-branch "ci/${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-${CI_COMMIT_REF_NAME:-$(git rev-parse \
            --abbrev-ref HEAD)}}}"
