name: Keploy Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  keploy-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Keploy CLI
        run: |
          curl --silent -O -L https://keploy.io/ent/install.sh \
            && source install.sh
      - name: Run Keploy Test Suite
        env:
          KEPLOY_API_KEY: ${{ secrets.TOKEN }}
        run: |
          export KEPLOY_API_KEY=${KEPLOY_API_KEY} && keploy test-suite \
            --app=925eafa6-1d13-4513-8057-654bb6e31a97 \
            --base-path https://playground.nileslabs.com/site.webmanifest \
            --cloud \
            --create-branch "ci/main-${{ github.run_number }}"
